name: resultk
description: resultk.dart impl of Result.kt
version: 1.0.0
homepage: https://github.com/boyan01/resultk.dart
author: boyan <yangbinyhbn@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  meta: ^1.1.7
dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
